 
version: '3.8'
services:
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    ports:
      - 9187:9187
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@host.docker.internal:5432/test?sslmode=disable"
