version: '3.8'
services:
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    ports:
      - 9187:9187
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@127.0.0.1:5432/test?sslmode=disable"
    network_mode: host
