version: '3.8'
services:
 
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    ports:
      - '9100:9100'
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host   # "host" to make the container accessible to the host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    