global:
  scrape_interval: 15s

scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
       - prometheus:9090
- job_name: node
  static_configs:
  - targets: ['IpOfNode:9100']
- job_name: postgres-exporter
  static_configs:
    - targets: ["postgres-exporterIp:9187"]